### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by aretecode**
Fixed missing semicolon

### CODE REVIEW

**Comment by pmjones** [comment]
I really appreciate your attention to these details. Many thanks.

**Comment by aretecode** [comment]
You're welcome, thank you for making it! I watched a couple talks on ADR so I wanted to make sure I understood it thoroughly. Taking 2,000 words of notes, doing some research & looking through each file helps me do that. Now I will do a little experiment and play around with ADR & some Aura libraries for my own example code.

**Comment by pmjones** [comment]
Right on. If you want a framework-ish example, check out Radar. https://github.com/radarphp/Radar.Adr  https://github.com/radarphp/Radar.Project (still in development)

**Comment by pmjones** [comment]
And if you have suggestions, or want to do a write-up, let me know. I'm always interested in feedback and improvements.

**Pull request merged**
